
server:
  servlet:
    context-path: /transaction-demo
  port: 8080

management:
  server:
    port: 10086
  endpoints:
    web:
      base-path: /admin
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_demo?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
